# Generated by Django 3.2.16 on 2023-09-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Maximum of 100 symbols', max_length=100, verbose_name='name')),
                ('description', models.TextField(help_text='Maximum of 1000 symbols', max_length=1000, verbose_name='description')),
                ('address', models.CharField(help_text='Maximum of 200 symbols', max_length=200, verbose_name='address')),
                ('coordinates', models.CharField(help_text='Maximum of 100 symbols', max_length=100, verbose_name='coordinates')),
                ('email', models.EmailField(help_text='Maximum of 254 symbols', max_length=254, verbose_name='email')),
                ('phone', models.CharField(help_text='Maximum of 15 symbols', max_length=15, verbose_name='phone')),
                ('website', models.CharField(help_text='Maximum of 200 symbols', max_length=200, verbose_name='website')),
                ('organization', models.CharField(help_text='Maximum of 200 symbols', max_length=200, verbose_name='organization')),
                ('inn', models.CharField(help_text='Maximum of 12 symbols', max_length=12, verbose_name='inn')),
            ],
        ),
    ]
