# Generated by Django 3.2.16 on 2023-09-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='address',
            field=models.CharField(blank=True, help_text='Maximum of 200 symbols', max_length=200, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='park',
            name='coordinates',
            field=models.CharField(blank=True, help_text='Maximum of 100 symbols', max_length=100, null=True, verbose_name='coordinates'),
        ),
        migrations.AlterField(
            model_name='park',
            name='description',
            field=models.TextField(blank=True, help_text='Maximum of 1000 symbols', max_length=1000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='park',
            name='email',
            field=models.EmailField(blank=True, help_text='Maximum of 254 symbols', max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='park',
            name='inn',
            field=models.CharField(blank=True, help_text='Maximum of 12 symbols', max_length=12, null=True, verbose_name='inn'),
        ),
        migrations.AlterField(
            model_name='park',
            name='name',
            field=models.CharField(blank=True, help_text='Maximum of 100 symbols', max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='park',
            name='organization',
            field=models.CharField(blank=True, help_text='Maximum of 200 symbols', max_length=200, null=True, verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='park',
            name='phone',
            field=models.CharField(blank=True, help_text='Maximum of 15 symbols', max_length=15, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='park',
            name='website',
            field=models.CharField(blank=True, help_text='Maximum of 200 symbols', max_length=200, null=True, verbose_name='website'),
        ),
    ]
